group Protect tax code
	TS -> TK : PUT /tokens
		rnote left
			__request body__
			{
				"pii": "//<tax code>//"
			}
		end note
					
	TK --> TS : HTTP 200 (ok)
		rnote left
			__response body__
			{
				"token": "//<tax code token>//"
			}
		end note
end
