openapi: 3.0.3

info:
  title: Services Microservice
  version: 1.0.0
  description: Handling of end-user services for Multi-channel Integration Layer of SW Client Project
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it

servers:
  - description: Services URL
    url: https://server_addr

security:
  - ApiKeyAuth: [ ]

paths:
  /services:
    get:
      operationId: getServices
      summary: Return the list of services available for end-users
      parameters:
        - $ref: 'common.yaml#/components/parameters/Version'
        - $ref: 'common.yaml#/components/parameters/AcquirerId'
        - $ref: 'common.yaml#/components/parameters/Channel'
        - $ref: 'common.yaml#/components/parameters/TerminalId'
      responses:
        "200":
          $ref: '#/components/responses/Services'
        "400":
          $ref: 'common.yaml#/components/responses/ConstraintViolation'
        "401":
          description: API key is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          description: Server error
        default:
          description: Unexpected error

components:
  schemas:
    Labels:
      description: Description of the service
      type: object
      additionalProperties: false
      properties:
        it:
          $ref: 'common.yaml#/components/schemas/Message'
        en:
          $ref: 'common.yaml#/components/schemas/Message'
        fr:
          $ref: 'common.yaml#/components/schemas/Message'
        de:
          $ref: 'common.yaml#/components/schemas/Message'
        es:
          $ref: 'common.yaml#/components/schemas/Message'
      required:
        - it
      example:
        it: "La tua posizione debitoria"
        en: "Your debt position"

    Service:
      description: Details of a service
      type: object
      additionalProperties: false
      properties:
        labels:
          $ref: '#/components/schemas/Labels'
        serviceId:
          $ref: 'common.yaml#/components/schemas/UUID'
      required:
        - labels
        - serviceId
      example:
        labels:
          it: "La tua posizione debitoria"
          en: "Your debt position"
        serviceId: "d0d654e6-97da-4848-b568-99fedccb642b"

  responses:
    Services:
      description: List of services retrieved successfully
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              services:
                type: array
                maxItems: 64
                items:
                  $ref: '#/components/schemas/Service'
            required:
              - services

  securitySchemes:
    ApiKeyAuth:
      $ref: 'common.yaml#/components/securitySchemes/ApiKeyAuth'