openapi: 3.0.3

info:
  title: PAN-to-Token Service and viceversa
  version: 6.0.0
  description: Service to create or retrieve, if it already exists, the token of a given PAN and viceversa
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it

servers:
  - description: PAN-to-Token Service URL
    url: https://server_addr

security:
  - ApiKeyAuth: [ ]

paths:
  /tokens:
    # ------------------------------------------------------
    # Creates or retrieves, if it already exists, the token
    # of a given PAN.
    # ------------------------------------------------------
    post:
      operationId: retrieveToken
      summary: Creates or retrieves, if it already exists, the token of a given PAN
      parameters:
        - $ref: 'common.yaml#/components/parameters/Version'
      requestBody:
        $ref: '#/components/requestBodies/RetrieveToken'
      responses:
        "200":
          $ref: '#/components/responses/TokenRetrieved'
        "201":
          $ref: '#/components/responses/TokenRetrieved'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: API key is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

  /pans/{panToken}:
    # ------------------------------------------------------
    # Retrieves the PAN of a given token.
    # ------------------------------------------------------
    get:
      operationId: getPan
      summary: Retrieves the PAN of a given token
      parameters:
        - $ref: 'common.yaml#/components/parameters/Version'
        - name: panToken
          description: Token of the PAN
          in: path
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/PanToken'
      responses:
        "200":
          $ref: '#/components/responses/PanRetrieved'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: API key is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: PAN not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

components:
  # ========================================================
  # Schemas
  # ========================================================
  schemas:
    # ------------------------------------------------------
    # Basic types
    # ------------------------------------------------------
    Pan:
      description: Payment card's PAN
      type: string
      pattern: "^\\d{16,19}$"
      example: "4769328596019370"

  # ========================================================
  # Request bodies
  # ========================================================
  requestBodies:
    # ------------------------------------------------------
    # For retrieveToken
    # ------------------------------------------------------
    RetrieveToken:
      description: Request to create or retrieve the token of a PAN
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              pan:
                $ref: '#/components/schemas/Pan'
            required:
              - pan
            example:
              pan: "4769328596019370"

  # ========================================================
  # Responses
  # ========================================================
  responses:
    # ------------------------------------------------------
    # For retrieveToken
    # ------------------------------------------------------
    TokenRetrieved:
      description: Token retrieved or created
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              panToken:
                $ref: 'common.yaml#/components/schemas/PanToken'
            required:
              - panToken
            example:
              panToken: "517a4216840E461fB011036A0fd134E1"

    # ------------------------------------------------------
    # For getPan
    # ------------------------------------------------------
    PanRetrieved:
      description: PAN retrieved
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              pan:
                $ref: '#/components/schemas/Pan'
            required:
              - pan
            example:
              pan: "4769328596019370"

  # ========================================================
  # Security schemes
  # ========================================================
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: This API uses API key
      name: X-API-Key
      in: header