openapi: 3.0.3

info:
  title: PM-Wallet Service
  version: 6.0.0
  description: Service to handle payment cards Wallet in the PagoPA Ecosystem
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it

servers:
  - description: PM-Wallet Service URL
    url: https://server_addr

security:
  - ApiKeyAuth: [ ]

paths:
  /cards/{panToken}/taxCode:
    # ------------------------------------------------------
    # Retrieve the tax code of the owner of the payment card
    # that has the PAN linked to the given token.
    # ------------------------------------------------------
    get:
      operationId: retrieveTaxCode
      summary: Retrieve the tax code of the owner of the payment card that has the PAN linked to the given token
      description: Retrieve the tax code by querying internal DB or invoking Bancomat, Nexi, SIA, Intesa Sanpaolo, Poste Italiane or ICCREA service
      parameters:
        - $ref: 'common.yaml#/components/parameters/Version'
        - name: panToken
          description: Token of the PAN
          in: path
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/PanToken'
      responses:
        "200":
          $ref: '#/components/responses/TaxCodeRetrieved'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: API key is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Tax code not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

  /cards:
    # ------------------------------------------------------
    # Retrieve the tax code of the owner of the payment card
    # that has the PAN linked to the given token.
    # ------------------------------------------------------
    post:
      operationId: presave
      summary: Pre-save a payment card in the Wallet
      parameters:
        - $ref: 'common.yaml#/components/parameters/Version'
      requestBody:
        $ref: '#/components/requestBodies/Presave'
      responses:
        "204":
          description: Ack
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: API key is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

  /enabledServices/{taxCode}/saveNewCards:
    # ------------------------------------------------------
    # Get the value of the flag "save new cards".
    # ------------------------------------------------------
    get:
      operationId: getSaveNewCardsFlag
      summary: Get the value of the flag "save new cards"
      parameters:
        - $ref: 'common.yaml#/components/parameters/Version'
        - name: taxCode
          description: Tax code
          in: path
          required: true
          schema:
            $ref: 'common.yaml#/components/schemas/TaxCode'
      responses:
        "200":
          $ref: '#/components/responses/SaveNewCardsFlagRetrieved'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: API key is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Tax code not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

components:
  # ========================================================
  # Request bodies
  # ========================================================
  requestBodies:
    # ------------------------------------------------------
    # For presave
    # ------------------------------------------------------
    Presave:
      description: Request to store the tax code of the owner of the payment card that has the PAN linked to the given token
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              panToken:
                $ref: 'common.yaml#/components/schemas/PanToken'
              taxCode:
                $ref: 'common.yaml#/components/schemas/TaxCode'
            required:
              - panToken
              - taxCode
            example:
              panToken: "517a4216840E461fB011036A0fd134E1"
              taxCode: "CHCZLN73D08A662B"

  # ========================================================
  # Responses
  ## ========================================================
  responses:
    # ------------------------------------------------------
    # For getSaveNewCardsFlag
    # ------------------------------------------------------
    SaveNewCardsFlagRetrieved:
      description: Flag retrieved
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              saveNewCards:
                type: boolean
            required:
              - saveNewCards
            example:
              saveNewCards: true

    # ------------------------------------------------------
    # For retrieveTaxCode
    # ------------------------------------------------------
    TaxCodeRetrieved:
      description: Tax code retrieved
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              taxCode:
                $ref: 'common.yaml#/components/schemas/TaxCode'
            required:
              - taxCode
            example:
              taxCode: "CHCZLN73D08A662B"

  # ========================================================
  # Security schemes
  # ========================================================
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: This API uses API key
      name: X-API-Key
      in: header