group Check acceptance of T&C
	SS -> TS : GET /acceptedTermsConds///<tax code token>//
		rnote left
			__header__
			- Version: //<api version>//
			- AcquirerId: //<acquirer id>//
			- Channel: //<channel>//
			- TerminalId: //<terminal id>//
		end note
		
	!include_many ../common/protect_tax_code.puml
	
	TS -> TC : readItem ( //<tax code token>// )
	
	TC --> TS : { "version": "//<t&c version>//" }
	
	TS -> TS : check //<t&c version>//
	
	TS --> SS : HTTP 200 (ok)
		rnote left
			__response body__
			{
				"outcome": "OK"
			}
		end note
end
